config/routes.rb
Rails.application.routes.draw do

	namespace :casein do
		resources :content_posts
		resources :categories
	end

  
  get '/' => 'application#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  
end

app/models/content_post.rb
class ContentPost < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/casein/categories_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class CategoriesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Categories'
  		@categories = Category.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View category'
      @category = Category.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new category'
    	@category = Category.new
    end

    def create
      @category = Category.new category_params
    
      if @category.save
        flash[:notice] = 'Category created'
        redirect_to casein_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new category'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update category'
      
      @category = Category.find params[:id]
    
      if @category.update_attributes category_params
        flash[:notice] = 'Category has been updated'
        redirect_to casein_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to update this category'
        render :action => :show
      end
    end
 
    def destroy
      @category = Category.find params[:id]

      @category.destroy
      flash[:notice] = 'Category has been deleted'
      redirect_to casein_categories_path
    end
  
    private
      
      def category_params
        params.require(:category).permit(:name, :category_id, :description, :permalink, :created, :update_id)
      end

  end
end

app/controllers/casein/content_posts_controller.rb
# Scaffolding generated by Casein v5.1.1.5

module Casein
  class ContentPostsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Content posts'
  		@content_posts = ContentPost.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View content post'
      @content_post = ContentPost.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new content post'
    	@content_post = ContentPost.new
    end

    def create
      @content_post = ContentPost.new content_post_params
    
      if @content_post.save
        flash[:notice] = 'Content post created'
        redirect_to casein_content_posts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new content post'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update content post'
      
      @content_post = ContentPost.find params[:id]
    
      if @content_post.update_attributes content_post_params
        flash[:notice] = 'Content post has been updated'
        redirect_to casein_content_posts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this content post'
        render :action => :show
      end
    end
 
    def destroy
      @content_post = ContentPost.find params[:id]

      @content_post.destroy
      flash[:notice] = 'Content post has been deleted'
      redirect_to casein_content_posts_path
    end
  
    private
      
      def content_post_params
        params.require(:content_post).permit(:title, :body, :post_id, :summary, :permalink, :string, :created, :edited, :owner_id)
      end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :casein, :action => :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/views/casein/categories/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :name %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :category_id %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :description %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :permalink %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_datetime_select f, f.object, :created %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :update_id %>
	</div>
</div>

app/views/casein/categories/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Name", :name %></th>
			<th><%= casein_sort_link "Category", :category_id %></th>
			<th><%= casein_sort_link "Description", :description %></th>
			<th><%= casein_sort_link "Permalink", :permalink %></th>
			<th><%= casein_sort_link "Created", :created %></th>
			<th><%= casein_sort_link "Update", :update_id %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% categories.each do |category| %>
		<tr>
			<td><%= casein_table_cell_link category.name, casein_category_path(category) %></td>
			<td><%= casein_table_cell_link category.category_id, casein_category_path(category) %></td>
			<td><%= casein_table_cell_link category.description, casein_category_path(category) %></td>
			<td><%= casein_table_cell_link category.permalink, casein_category_path(category) %></td>
			<td><%= casein_table_cell_link category.created, casein_category_path(category) %></td>
			<td><%= casein_table_cell_link category.update_id, casein_category_path(category) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_category_path(category), :method => :delete, :data => { :confirm => "Are you sure you want to delete this category?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/categories/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Categories<%= casein_pagination_details @categories %></h2>

<%= render :partial => 'casein/categories/table', :locals => { :categories => @categories } %>

<div class="text-center">
	<%= will_paginate @categories %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new category".html_safe, new_casein_category_path %></li>

<% end %>

app/views/casein/categories/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new category</h2>

<%= form_for @category, :url => casein_categories_path do |f| %>
	
	<%= render :partial => 'casein/categories/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_categories_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new category", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_categories_path %></li>
<% end %>

app/views/casein/categories/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View category</h2>

<%= form_for @category, :url => casein_category_path(@category) do |f| %>

	<%= render :partial => 'casein/categories/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_categories_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_categories_path %></li>
<% end %>

app/views/casein/content_posts/_form.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :title %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :body %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :post_id %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :summary %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :permalink %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :string %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_datetime_select f, f.object, :created %>
	</div>
	<div class="col-lg-6">
		<%= casein_datetime_select f, f.object, :edited %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :owner_id %>
	</div>
	<div class="col-lg-6">
		
	</div>
</div>

app/views/casein/content_posts/_table.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Title", :title %></th>
			<th><%= casein_sort_link "Body", :body %></th>
			<th><%= casein_sort_link "Post", :post_id %></th>
			<th><%= casein_sort_link "Summary", :summary %></th>
			<th><%= casein_sort_link "Permalink", :permalink %></th>
			<th><%= casein_sort_link "String", :string %></th>
			<th><%= casein_sort_link "Created", :created %></th>
			<th><%= casein_sort_link "Edited", :edited %></th>
			<th><%= casein_sort_link "Owner", :owner_id %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% content_posts.each do |content_post| %>
		<tr>
			<td><%= casein_table_cell_link content_post.title, casein_content_post_path(content_post) %></td>
			<td><%= casein_table_cell_link content_post.body, casein_content_post_path(content_post) %></td>
			<td><%= casein_table_cell_link content_post.post_id, casein_content_post_path(content_post) %></td>
			<td><%= casein_table_cell_link content_post.summary, casein_content_post_path(content_post) %></td>
			<td><%= casein_table_cell_link content_post.permalink, casein_content_post_path(content_post) %></td>
			<td><%= casein_table_cell_link content_post.string, casein_content_post_path(content_post) %></td>
			<td><%= casein_table_cell_link content_post.created, casein_content_post_path(content_post) %></td>
			<td><%= casein_table_cell_link content_post.edited, casein_content_post_path(content_post) %></td>
			<td><%= casein_table_cell_link content_post.owner_id, casein_content_post_path(content_post) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_content_post_path(content_post), :method => :delete, :data => { :confirm => "Are you sure you want to delete this content post?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/content_posts/index.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Content posts<%= casein_pagination_details @content_posts %></h2>

<%= render :partial => 'casein/content_posts/table', :locals => { :content_posts => @content_posts } %>

<div class="text-center">
	<%= will_paginate @content_posts %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new content post".html_safe, new_casein_content_post_path %></li>

<% end %>

app/views/casein/content_posts/new.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>Add a new content post</h2>

<%= form_for @content_post, :url => casein_content_posts_path do |f| %>
	
	<%= render :partial => 'casein/content_posts/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_content_posts_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new content post", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_content_posts_path %></li>
<% end %>

app/views/casein/content_posts/show.html.erb
<!-- Scaffolding generated by Casein v5.1.1.5 -->

<h2>View content post</h2>

<%= form_for @content_post, :url => casein_content_post_path(@content_post) do |f| %>

	<%= render :partial => 'casein/content_posts/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_content_posts_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_content_posts_path %></li>
<% end %>

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-content_posts"><%= link_to "Content posts", casein_content_posts_path %></li>
<li id="tab-categories"><%= link_to "Categories", casein_categories_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "TERT", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>